### ISSUE TITLE
As a user, I can filter skills based on max level, members only, and other attributes

### ISSUE THREAD

**Issue by benrandall** [benrandall/idb#144]
- User should be able to interact with easy-to-understand UI elements
- Should work in conjunction with ordering and searching

Story points estimation: 5 (hours)

**Comment by benrandall** [comment]
Possibly save max level for searching?

**Comment by simplyluke** [comment]
Backend supports this

**Comment by clairebingham** [comment]
Took about 5 hours for the front end
