### ISSUE TITLE
As a customer, I can view technical documentation on the filtering and sorting

### ISSUE THREAD

**Issue by benrandall** [benrandall/idb#146]
- Updated gitbook technical documentation on filtering and sorting
- Must also update for searching

Story points estimation: 1

**Comment by benrandall** [comment]
Need other's input on how we implemented filtering and sorting!

**Comment by simplyluke** [comment]
I've updated the filtering and searching documentation to reflect the backend implementation and API endpoints. Sorting is handled by the frontend and @clairebingham  and @elmdecoste are handling updating that documentation. This took me about .5 hours.
