### ISSUE TITLE
As a user, I can navigate back and forth through model pages

### ISSUE THREAD

**Issue by benrandall** [benrandall/idb#148]
- Implement pagination using React

Story points estimation: 5 (hours)

**Comment by benrandall** [comment]
Works for model pages, but not for search results right now?

**Comment by dylanlramage** [comment]
Should work for search results as well

**Comment by clairebingham** [comment]
We can reduce this estimate to a 3, was a built in react component

**Comment by elmdecoste** [comment]
Agreed ^ pagination was simpler than we initially thought
