### ISSUE TITLE
As a user, I should not be able to add the same filter twice

### ISSUE THREAD

**Issue by connormlewis** [benrandall/idb#180]
If you click the dropdown for a filter, and select an item. That item shouldn't appear in the list if you try to select another filter. Current behavior allows for the filter to be applied more than once.

**Comment by clairebingham** [comment]
![image](https://user-images.githubusercontent.com/8785376/38898996-3424d404-425c-11e8-880b-00b7d0811fed.png)
screenshot for reference, @elmdecoste not exactly sure how to fix this one upon first look

**Comment by benrandall** [comment]
Estimated Time: 2 hours

**Comment by benrandall** [comment]
Actual Time: 1 hour
