### ISSUE TITLE
As a user, I should have a pleasant experience when navigating to the about page

### ISSUE THREAD

**Issue by connormlewis** [benrandall/idb#183]
Currently, the page takes a long time to load every time it is navigated to. This could benefit from caching whatever is taking a long time to load (possibly the GitHub API call). Also, the loading indicator is partially hidden behind the navigation bar. This should be centered on the screen or otherwise readily visible.

**Comment by benrandall** [comment]
#123

**Comment by benrandall** [comment]
Estimated Time: 2 hours

**Comment by benrandall** [comment]
Actual Time: .5 hour
