### ISSUE TITLE
As a user, I can navigate through the application flawlessly due to full coverage and effective application testing

### ISSUE THREAD

**Issue by clairebingham** [benrandall/idb#87]
-Includes Postman API testing, Mocha JS Unit Testing, Pythong unittest unit testing, GUI acceptance tests using Selenium

-Story points estimation: 13 (~3 per testing suite)

**Comment by clairebingham** [comment]
Relates to #81, #82, #83, #84

**Comment by elmdecoste** [comment]
The application should be good to test now!

@dylanlramage  should be on Selenium
@benrandall  Should be on unit

**Comment by simplyluke** [comment]
My unittests for python + postman tests took about 5 hours in total - we ended up with 94% coverage on main.py
