### ISSUE TITLE
As a customer, I can see updated documentation pertaining to Phase 2 in the Gitbook report

### ISSUE THREAD

**Issue by clairebingham** [benrandall/idb#88]
-Update our gitbook documentation to reflect changes in Phase 2 
-This includes updated API documentation (any API changes, formatted in multi-page layout, include error responses), critiques, and overall docs

Story points estimation: 5

**Comment by elmdecoste** [comment]
Let's get this done moderately soon, we need to make sure the API docs get cleaned up for this round

**Comment by simplyluke** [comment]
This has been completed - 3 hours from what @benrandall told me and my input
