### ISSUE TITLE
As a customer, I can request meaningful responses from the Runescrape API so that I can use them in my own services/application

### ISSUE THREAD

**Issue by clairebingham** [benrandall/idb#90]
-i.e. if our front end is the customer, we should be able to make requests to our backend API service to meaningfully populate our front end

Story points estimation: 5

**Comment by elmdecoste** [comment]
@stevendiaz thanks for updating the about page API, really helped on the frontend

**Comment by simplyluke** [comment]
This is documented and complete now - it took about 7 hours
